# Modified and renamed by Graphcore Ltd.
- name: Create or destroy appliance
  hosts: openstack
  vars:
    image_name: "{{ poplar_appliance_images | selectattr('name', 'equalto', operating_system) | map(attribute='image_name') | first }}"
    image_tag: "{{ poplar_appliance_images | selectattr('name', 'equalto', operating_system) | map(attribute='image_tag') | first }}"
    execution_order:
      - "{{ (terraform_state == 'present' or terraform_state == 'absent') | ternary('init_infra','') }}"
      - "{{ (terraform_state == 'present') | ternary('ipum_infra','') }}"
      - "{{ (terraform_state == 'present' or terraform_state == 'absent') | ternary('poplar_infra','') }}"
      - "{{ (terraform_state == 'absent' ) | ternary('ipum_infra','') }}"

  tasks:
    - name: Include the roles needed
      ansible.builtin.include_role:
        name: "{{ role_var }}"
      loop: "{{ execution_order | select | list }}"
      loop_control:
        loop_var: role_var

# Write the outputs as the final task
- hosts: localhost
  tasks:
    - debug: var=outputs
      vars:
        outputs:
          cluster_access_ip: "{{ hostvars[groups['openstack'][0]].cluster_access_ip }}"
          cluster_user: "{{ hostvars[groups['openstack'][0]].appliance_user }}"
          cluster_flavour_name: "{{ hostvars[groups['openstack'][0]].cluster_flavour_name }}"
          cluster_operating_system: "{{ hostvars[groups['openstack'][0]].operating_system }}"
          allocation_name: "{{ hostvars[groups['openstack'][0]].allocation_name }}"
          allocation_size: "{{ hostvars[groups['openstack'][0]].allocation_size }}"
          ipuof_vipu_api_partition_id: "{{ hostvars[groups['openstack'][0]].user_partition | default('none') }}"
          ipuof_vipu_api_host: "{{ hostvars[groups['openstack'][0]].vipu_servers['default' if '@' in appliance_tenancy else appliance_tenancy]['ctrl_net_ip'] }}"
