# This task list deconfigures partitions, allocations and IPUMs when the Poplar
# Appliance is torn down (terraform_state == absent)

# This is flakey, if allocation_name isn't known it throws an error so we
# check the error condition before trying to execute the following block.
- name: List partitions in our allocation (only)
  ansible.builtin.command:
    cmd: "{{ vipu_server_ssh }} vipu-admin list partitions --allocation {{allocation_name}} --showjson"
  when: allocation_size | int > 0
  register: vipu_partition_out
  ignore_errors: true

- name: Partition removal block
  block:
    - name: Convert partition_out to list
      ansible.builtin.set_fact:
        vipu_partition_list: "{{ vipu_partition_out.stdout | from_json | community.general.json_query('partitions[*].id') | list }}"
      when: vipu_partition_out.rc == 0

    - name: Remove partitions in our allocation
      ansible.builtin.command:
        cmd: "{{ vipu_server_ssh }} vipu-admin remove partition {{ part_var }} --force"
      loop: "{{ vipu_partition_list if vipu_partition_list else [] }}"
      loop_control:
        loop_var: part_var
      register: partition_remove_out
      when:
        - vipu_partition_list is defined
        - vipu_partition_list is iterable
  # End block
  when:
    - allocation_size | int > 0

- name: List allocation - the return code shows if the expected alloc exists
  ansible.builtin.command:
    cmd: "{{ vipu_server_ssh }} vipu-admin --showjson get allocation {{allocation_name}}"
  when: allocation_size | int > 0
  register: vipu_alloc_list
  ignore_errors: true

- name: Remove allocation block
  block:
    - name: List assigned IPUMs cos we need it for the truffle-shuffle
      ansible.builtin.set_fact:
        assigned_ipums_list: "{{ vipu_alloc_list.stdout | from_json |  moreati.jq.jq('.allocation.spec.agent_ids') }}"
      when: vipu_alloc_list.rc == 0

    - name: Remove allocation
      ansible.builtin.command:
        cmd: "{{ vipu_server_ssh }} vipu-admin remove allocation {{ allocation_name }}"
      register: allocation_remove_out
      # Don't fail if the allocation was never created due to lack of space
      failed_when: "allocation_remove_out.rc != 0 and 'is unknown' not in allocation_remove_out.stderr"

    # Remove the IPUMs in assigned_ipums_list from the user's vpod
    - name: Shuffle IPUMs back to staging
      ansible.builtin.include_role:
        name: ipum_infra
        tasks_from: truffleshuffle.yml
  when:
    - allocation_size | int > 0
