# This task list deconfigures partitions, allocations and IPUMs when the Poplar
# Appliance is torn down (terraform_state == absent)

- name: If ipum_model is 'meh' we need to find if we're on bow or classic
  # TODO: we need to lookup the correct vipu_server here?
  ansible.builtin.shell: |
    {{ vipu_server_ssh }} vipu-admin get allocation {{allocation_name}} #{{item}}
  register: ipum_model_scan
  when: ipum_model_scan.rc|default(1) != 0
  ignore_errors: true
  loop: "{{ (ipum_model == 'any') | ternary( 'classic,bow', ipum_model ) | split(',') }}"

- name: Debug allocation_result
  ansible.builtin.debug:
    var: ipum_model_scan

- name: Set the ipum actual model from user choice
  ansible.builtin.set_fact:
    ipum_model_actual: "{{ ipum_model }}"

- name: Work out whether we allocated classic or bow with meh set
  ansible.builtin.set_fact:
    ipum_model_actual: "{{ ipum_model_scan.results | rejectattr('rc', 'undefined')| selectattr('rc', '==', 0) | map(attribute='item')  | first | default('any') }}"
  when: ipum_model is search('any')

# This is flakey, if allocation_name isn't known it throws an error so we
# check the error condition before trying to execute the following block.
- name: List partitions in our allocation (only)
  ansible.builtin.command:
    # TODO: use ipum_model_actual to lookup which vipu_server_ssh to use? or have two appliances?
    cmd: "{{ vipu_server_ssh }} vipu-admin -H localhost -P {{ vipu_container_admin_port }} list partitions --allocation {{allocation_name}} --showjson"
  when:
    - allocation_size | int > 0
    - not ipum_model_actual is search('any')
  register: vipu_partition_out
  ignore_errors: true

- name: Partition removal block
  block:
    - name: Convert partition_out to list
      ansible.builtin.set_fact:
        vipu_partition_list: "{{ vipu_partition_out.stdout | from_json | community.general.json_query('partitions[*].id') | list }}"

    - name: Remove partitions in our allocation
      ansible.builtin.command:
        cmd: "{{ vipu_server_ssh }} vipu-admin -H localhost -P {{ vipu_container_admin_port }} remove partition {{ part_var }} --force"
      loop: "{{ vipu_partition_list if vipu_partition_list else [] }}"
      loop_control:
        loop_var: part_var
      register: partition_remove_out
      when:
        - vipu_partition_list is defined
        - vipu_partition_list is iterable
  # End block
  when:
    - allocation_size | int > 0
    - vipu_partition_out.rc is defined and vipu_partition_out.rc == 0

- name: List allocation - the return code shows if the expected alloc exists
  ansible.builtin.command:
    cmd: "{{ vipu_server_ssh }} vipu-admin --showjson get allocation {{allocation_name}}"
  when: allocation_size | int > 0
  register: vipu_alloc_list
  ignore_errors: true

- name: Remove allocation block
  block:
    - name: List assigned IPUMs cos we need it for the truffle-shuffle
      ansible.builtin.set_fact:
        assigned_ipums_list: "{{ vipu_alloc_list.stdout | from_json |  moreati.jq.jq('.allocation.spec.agent_ids') }}"
        #when: vipu_alloc_list.rc == 0

    - name: Remove allocation
      ansible.builtin.command:
        cmd: "{{ vipu_server_ssh }} vipu-admin remove allocation {{ allocation_name }}"
      register: allocation_remove_out
      # Don't fail if the allocation was never created due to lack of space
      failed_when: "allocation_remove_out.rc != 0 and 'is unknown' not in allocation_remove_out.stderr"

    # Remove the IPUMs in assigned_ipums_list from the user's vpod
    - name: Shuffle IPUMs back to staging
      ansible.builtin.include_role:
        name: ipum_infra
        tasks_from: truffleshuffle.yml
      # if we don't have assigned_ipums_list then we don't have IPUMs
      # TODO: ideally we can detect if there are instances and error out?
      when: assigned_ipums_list is defined
  when:
    - allocation_size | int > 0
    - vipu_alloc_list.rc is defined and vipu_alloc_list.rc == 0
